### PR TITLE
Allow changing quote_char from evaluator

### PR DESCRIPTION
**Pull request by jamesattewell**
Hi @m-peko,

This change allows quote_char to be specified from evaluator as template parameter, defaulted to double_quote_char. 

Please note that these changes make booleval a header only library so I have changed the CMake files and they work although I am not sure if I have done this in the correct way.

Cheers

James

### CODE REVIEW

**Comment by m-peko** [comment]
Hi @jamesattewell,
Sorry for not taking a look at this PR. I will do it in the next few days. I was just very very busy these days.
Sorry once again.

**Comment by jamesattewell** [comment]
Hi @m-peko. No worries, its not urgent. I have been using booleval with this PR included and it is working well for me.

You did mention about changing around the structure of the code to make this easier, referenced in PR #49, but at least this gets us to a point where its usable.

**Comment by m-peko** [comment]
Hi @jamesattewell, sorry for not responding for a very long time. I would like to delay merge of this PR until I make all the functionalities compile time functionalities and then everything will be header-only.
Thanks

**Comment by jamesattewell** [comment]
Hi @m-peko.

Ok, no worries. This PR does make booleval header only if you have a look at it.

Cheers

James

**Comment by m-peko** [comment]
I have closed this since v2.0.0 is coming out and it will change some stuff so we can make feature request on this.

**Pull request closed without merging**
